version: '3.8'
services:
  db:
    image: postgis/postgis:latest
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root_sesac
      POSTGRES_DB: test_db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: