version: '3.8'
services:
  db:
    image: postgis-sloped
    hostname: localhost
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root_sesac
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

volumes:
  postgres-data: