spring:
  config:
    activate.on-profile: local
    import: optional:file:.env.local[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: sas13975555@gmail.com
    password: atgzaccqrtqzqiwy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true





logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
