spring:
  config:
    activate.on-profile: local
    import: optional:file:.env.local[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    format_sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

---

spring:
  config:
    activate.on-profile: prod
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    format_sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG